version: "3"
services:
  node-app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    depends_on:
      - mongo
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: swag
      MONGO_INITDB_ROOT_PASSWORD: pass
    volumes:
      - mongo-db:/data/db
  redis: 
    image: redis
#naming all the volumes to be created
volumes:
  mongo-db: