version: "3"
services:
  node-app:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=swag
      - MONGO_PASSWORD=pass
      - SESSION_SECRET=secret
    command: npm run dev
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: swag
      MONGO_INITDB_ROOT_PASSWORD: pass
