version: '3'
services: 
  node-app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./:/app #bind mount
      - ./app/node_modules #anonymous mount
    environment:
      - PORT=3000
    # env_file:
    #   - ./.env